### ISSUE TITLE
Video drivers crash if too many webcams are active

### ISSUE THREAD

**Issue by BradF-99** [monkey-team-3801/on-board#103]
**Describe the bug**
When viewing approximately 10 webcams at once, it crashes my video drivers entirely. @aXises has reported it happening on Chrome and @JZ4012 has reported it happening on Firefox - potentially an NVIDIA driver problem?

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to a video-enabled room
2. Have multiple webcams open
3. System will crash

**Expected behaviour**
System not to crash.

**Additional context**
System runs Windows 10 Pro v2004 build 19041.388, NVIDIA Studio Driver version 456.38. Browser is Brave Version 1.14.84 Chromium: 85.0.4183.121 (Official Build) (64-bit)

**Comment by JZ4012** [comment]
Thank you for the report, this is a high priority task and we will investigate immediately.

**Comment by BradF-99** [comment]
I can test on my laptop if needed, it has an AMD FirePro GPU so we can rule out NVIDIA drivers being an issue.

**Comment by JZ4012** [comment]
That would be very much appreciated @BradF-99 , thank you for taking the time to verify.

**Comment by aXises** [comment]
Hi @BradF-99, we are proud to announce that this issue is currently being looked in to by our top engineer.

Stay posted for the latest updates, make sure you are watching and subscribed so you don't miss out on any events!

Kind regards,
Management

**Comment by BradF-99** [comment]
Also might be a good idea to test with non-Chromium based browsers and different operating systems to rule out variables that could cause or contribute to this issue.

**Comment by aXises** [comment]
> Also might be a good idea to test with non-Chromium based browsers and different operating systems to rule out variables that could cause or contribute to this issue.

Hi @BradF-99, we currently do not support non-Chromium based browsers and operating systems which lack software such as Linux. We do currently support Windows 10, Windows 8 and Windows 7 and will continue supporting them for the coming years. Windows Vista and Windows XP support will be removed soon.

Kind Regards,
Management

**Comment by aXises** [comment]
Hi, @BradF-99 Hi Windows XP and Windows Vista support has been removed as of 4 pm AEST.

Kind Regards,
Management
