### ISSUE TITLE
Feature request - Notification when instructor posts a question

### ISSUE THREAD

**Issue by BradF-99** [monkey-team-3801/on-board#114]
**Specifications**
When the instructor or tutor posts a question, it would be beneficial if there was a pop-up (maybe accompanied with a notification sound) to let students know a new question is available to be answered.

**Comment by aXises** [comment]
Thank you very much for the suggestion, this is a highly requested feature of on-board which we will definitely be adding for the MVP, stay tuned!

Kind Regards,
Management

**Comment by JZ4012** [comment]
Hi @BradF-99 , 
I would like to inform you that this feature will be included in the next responses update, thank you for the suggestion!
