### ISSUE TITLE
Classroom popup box not appearing in Firefox

### ISSUE THREAD

**Issue by JZ4012** [monkey-team-3801/on-board#118]
**Describe the bug**
Popup box does not appear in Firefox when creating a new classroom.

**To Reproduce**
Steps to reproduce the behaviour:

1. Create a new classroom in Firefox.

**Expected behaviour**
A popup box indicating the classroom has opened.

**Browser (please complete the following information):**

-   Firefox

**Additional context**
tony pls fix

**Comment by aXises** [comment]
Hi, our CTO has advised us that we only support chromium browsers.

Kind Regards,
Management
