### ISSUE TITLE
Request entity too large returning status 200 OK

### ISSUE THREAD

**Issue by Assasindie** [monkey-team-3801/on-board#123]
**Describe the bug**
When trying to create an announcement that is too large, the server responds with status code 200 and says the announcement is scheduled. However, the announcement is never displayed because the entity is too large.

**To Reproduce**
Steps to reproduce the behaviour:

1. Create an announcement with a lot of letters
2. Click create
3. The website will say the announcement is successfully scheduled.
4. Refresh the page
5. The announcement does not appear

**Expected behaviour**
The successfully scheduled text should not appear and should notify the user that the announcement is too large. The server should return code 413 Payload Too Large not 200 OK.

**Screenshots**
![image](https://user-images.githubusercontent.com/24616302/95418161-3680c180-097a-11eb-8f9b-277b13885970.png)
![image](https://user-images.githubusercontent.com/24616302/95418166-3c76a280-097a-11eb-94c3-0e5d52bd07de.png)
![image](https://user-images.githubusercontent.com/24616302/95418372-b3ac3680-097a-11eb-9199-f19bf22a3b32.png)

**Browser (please complete the following information):**

Chrome

**Comment by aXises** [comment]
Hi, thank you for reporting this issue. We are planning to do a run-through of all request/response related issues soon.

Kind regards,
Management

**Comment by aXises** [comment]
Due to economical issues, we are closing low priority issues such as authentication.

Kind Regards,
Management
