### ISSUE TITLE
Avatar system

### ISSUE THREAD

**Issue by aXises** [monkey-team-3801/on-board#39]
**Specifications**
The proposal indicates a live avatar system.

We will need to determine the possibility of this.

Worse case we simply allow users to upload fixed images.

**Comment by JZ4012** [comment]
The live avatar system will not be implemented. Users will need to upload their own images or choose a default avatar.

**Comment by aXises** [comment]
Can you include the section in the report where you found that, just so people won't bring this up again and we have justification

**Comment by JZ4012** [comment]
See page 69, heading "Analytics on Feasibility". Although it was not explicitly said that it was infeasible, the live avatar system would require facial recognition and machine learning techniques in order to fully implement, which is not within our scope.
