### ISSUE TITLE
Able to impersonate users in private chat

### ISSUE THREAD

**Issue by Assasindie** [monkey-team-3801/on-board#86]
**Describe the bug**
By doing a POST request to https://on-board-prod.herokuapp.com/chat/newMessage I am able to send a message to a chat room using any username regardless of who I am logged in as. This violates one of the 3 security principles (Integrity).

**To Reproduce**
Steps to reproduce the behaviour:

1. Make a POST request to https://on-board-prod.herokuapp.com/chat/newMessage and edit the sendUser field of the request JSON to whatever you like.
2. Reload the room page
3. See the message has been sent with the modified username.

**Expected behaviour**
The server would display the message with the current username I am logged in as.

**Screenshots**
![image](https://user-images.githubusercontent.com/24616302/92989383-59ed5380-f517-11ea-8744-8856b3fd20a4.png)

![image](https://user-images.githubusercontent.com/24616302/92989455-e566e480-f517-11ea-9d20-21c9d7f1edb8.png)

**Browser (please complete the following information):**

Not browser specific.

**Comment by aXises** [comment]
Thank you for reporting this bug, a monkey will take a look into this issue ASAP.

**Comment by aXises** [comment]
Due to economical issues, we are closing low priority issues such as authentication.

Kind Regards,
Management

**Comment by aXises** [comment]
Recent investments have allowed us to spare the resources to address this issue. Our lead engineer will give you a full report within the next week.

Kind Regards,
Management
