### ISSUE TITLE
No authentication done on message send

### ISSUE THREAD

**Issue by Assasindie** [monkey-team-3801/on-board#87]
**Describe the bug**
I am able to send messages using the POST request to https://on-board-prod.herokuapp.com/chat/newMessage without the correct token. 

**To Reproduce**
Steps to reproduce the behaviour:

1. Make a POST request to https://on-board-prod.herokuapp.com/chat/newMessage and edit the Authorization field of the request JSON to anything besides your original token. Working code is attached simply paste and run in the browsers console.
2. Reload the room page
3. See message has been sent even though the token was incorrect.

**Expected behaviour**
The server should return a 401 unauthorized error and the message should not be sent.

**Screenshots**
![image](https://user-images.githubusercontent.com/24616302/92989651-fb28d980-f518-11ea-8c5f-57d84bef8042.png)
![image](https://user-images.githubusercontent.com/24616302/92989661-0bd94f80-f519-11ea-8407-906f951b1382.png)

**Browser (please complete the following information):**
Not browser specific

**Additional context**
Working request - 
fetch("https://on-board-prod.herokuapp.com/chat/newMessage", {
  method: 'POST',
  body: JSON.stringify({sendUser:'aXises',content:'Invalid Token Test ',sessionId:'5f5a59f36b360729d874e3ce',sentTime:'2020-09-05T11:55:08.613Z'}),
  headers: {'Content-Type': 'application/json', 'Authorization' : 'Bearer this is not a token'},}).then(response => console.log(response));

**Comment by BradF-99** [comment]
The newMessage endpoint doesn't use the auth token.

**Comment by Assasindie** [comment]
The request from the website will still send the token as seen in this picture.
![image](https://user-images.githubusercontent.com/24616302/92989733-bf424400-f519-11ea-84bd-b5c0e5fa4a5f.png)
So it is still not checking if the user is authorized to send the message.

**Comment by aXises** [comment]
Thank you for reporting this issue, I will look into it immediately after browsing reddit.

**Comment by aXises** [comment]
Due to economical issues, we are closing low priority issues such as authentication.

Kind Regards,
Management

**Comment by aXises** [comment]
Recent investments have allowed us to spare the resources to address this issue. Our lead engineer will give you a full report within the next week.

Kind Regards,
Management
