### ISSUE TITLE
No server-side validation for course enrolment

### ISSUE THREAD

**Issue by BradF-99** [monkey-team-3801/on-board#88]
**Describe the bug**
A user can bypass the client-side course code validation for enrolment and create their own courses. Additionally, it might be possible for a user to change another users enrolled courses (untested).

**To Reproduce**
Steps to reproduce the behaviour:

1. Create and send a POST request to the /user/enrol endpoint that includes the "courses" header object.
2. Refresh page.

**Expected behaviour**
Assuming server should return HTTP status code 400.

**Screenshots**
![image](https://user-images.githubusercontent.com/37586752/92991009-f584c100-f523-11ea-999c-c6ea1d74087b.png)

**Browser (please complete the following information):**

-   Brave Version 1.13.86 Chromium: 85.0.4183.102 (Official Build) (64-bit)

**Additional context**
Unknown if this is intended behaviour.

**Comment by aXises** [comment]
Due to economical issues, we are closing low priority issues such as authentication.

Kind Regards,
Management

**Comment by aXises** [comment]
Recent investments have allowed us to spare the resources to address this issue. Our lead engineer will give you a full report within the next week.

Kind Regards,
Management
