### ISSUE TITLE
Feature Request: View which tutors are online 

### ISSUE THREAD

**Issue by BradF-99** [monkey-team-3801/on-board#96]
**Specifications**
I think it would be a good idea to view which tutors are available / online per unit, in case I need to contact the teaching staff with an urgent query.

**Comment by aXises** [comment]
Thank you very much for your suggestion, we considered this approach previously but parts of the specification hinted at the removal of this feature.

However, as there have been multiple requests to make this feature a priority, we will consider bringing this back.

Once again, thank you for your interest in *On Board*.

We hope to see you at the Expo!

Kind regards,
Management

**Comment by aXises** [comment]
@BradF-99 Hello Mr BradF this is to let you know we have considered accepting your feature request, one of our members will take care of this.

Thank you again for your interest in on-board.
Kind Regards,
Management

**Comment by aXises** [comment]
Hello @BradF-99, we have reopened an existing ticket related to this (https://github.com/monkey-team-3801/on-board/issues/23).

@Kas-kb please keep in touch with our client @BradF-99, he has been very helpful both in the testing and evaluation of our product. I'm sure he will have beneficial feedback for you regarding your implementation.

Kind Regards,
Management
